apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ai-canary-demo
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: ai-canary-demo

  namespaceSelector:
    matchNames:
      - ai-canary

  endpoints:
    - port: http
      path: /metrics
      interval: 5s
      honorLabels: true
